export default [
  "Lorem",
  "ipsum",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Adjective",
    result: "beautiful",
  },
  "dolor",
  "sit",
  "amet,",
  "consectetur",
  "adipiscing",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Noun",
    result: "boy",
  },
  "elit,",
  "sed",
  "do",
  "eiusmod",
  "tempor",
  "incididunt",
  "ut",
  "labore",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Verb",
    result: "run",
  },
  "et",
  "dolore",
  "magna",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Adverb",
    result: "good catch",
  },
  "aliqua.",
  "Ut",
  "enim",
  "ad",
  "minim",
  "veniam,",
  "quis",
  "nostrud",
  "exercitation",
  "ullamco",
  "laboris",
  "nisi",
  "ut",
  "aliquip",
  "ex",
  "ea",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Place",
    result: "paris",
  },
  "commodo",
  "consequat.",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Adverb",
    result: "good touch",
  },
  "Duis",
  "aute",
  "irure",
  "dolor",
  "in",
  "reprehenderit",
  "in",
  "voluptate",
  "velit",
  "esse",
  "cillum",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Person",
    result: "henry",
  },
  "dolore",
  "eu",
  "fugiat",
  "nulla",
  "pariatur.",
  "Excepteur",
  "sint",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Place",
    result: "tokyo",
  },
  "occaecat",
  "cupidatat",
  "non",
  "proident,",
  "sunt",
  "in",
  "culpa",
  "qui",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Idiom",
    result: "sweet like butter",
  },
  "officia",
  "deserunt",
  "mollit",
  "anim",
  "id",
  "est",
  {
    tag: "span",
    className:
      "text-white bg-gray-900 text-center text-md font-semibold px-3 py-1 mr-1 rounded-md",
    text: "Clause",
    result: "ohh no ohh no",
  },
  "laborum.",
];
